### ISSUE TITLE
Wrong line endings after installation

### ISSUE THREAD

**Issue by colinaaa** [ManiaciaChao/qq-group-cli#1]
After `yarn global install ...`, I got:

```
env: node\r: No such file or directory
```

seems that `npm` will auto change the ending, but `yarn` will not.

see: https://github.com/yarnpkg/yarn/issues/5480

**Comment by ManiaciaChao** [comment]
Now I use github actions to publish within a linux platform. Should fix this issue :)

**Comment by colinaaa** [comment]
It fixes! Appreciate that.
